"""lazy_core — PEP 562 lazy facade over the decomposed lazy_core package.

`lazy-core-package-decomposition` split the former flat
`user/scripts/lazy_core.py` monolith into the 12 seam submodules below.
This `__init__.py` is the facade that keeps every existing import site
working byte-compatibly:

    import lazy_core
    from lazy_core import _atomic_write
    lazy_core.notify_halt(...)
    lazy_core.time = fake_time            # module-attribute monkeypatching

Every public AND used-private name that used to live directly on the
`lazy_core` module is resolved lazily via `__getattr__` below, forwarding to
whichever submodule owns it. As of Phase-5 WU-4 the `_SUBMODULE_BY_NAME` map
is EXPLICIT-TOTAL: `_monolith.py` is deleted and there is NO fallback
submodule — an unmapped name raises a clean AttributeError
(`test_facade_map_total_and_collision_free` pins totality, per-name
resolution, and definition-site uniqueness).

This facade is PERMANENT, not a transitional shim slated for removal.

CRITICAL — patchability contract: a forwarded attribute is NEVER memoized
into this module's globals. Tests patch `lazy_core.<submodule>.<name>` (the
module where the name actually resolves); if `__getattr__` cached the
forwarded value here, a later `<submodule>.X = fake` patch would be invisible
to the next `lazy_core.X` read. Only the submodule import itself is cached
(automatically, via `sys.modules`) — never the attribute lookup.
"""

import importlib

from ._ctx import _DIAGNOSTICS

# The EXPLICIT-TOTAL name -> submodule map (Phase-5 WU-4): one entry per
# top-level name defined in a submodule (scripted AST generation; the
# collision check in test_facade_map_total_and_collision_free hard-fails a
# name defined in two submodules). There is no fallback submodule.
_SUBMODULE_BY_NAME: dict[str, str] = {
    "_DIAGNOSTICS": "_ctx",
    "_diag": "_ctx",
    "clear_diagnostics": "_ctx",
    "_atomic_write": "_ctx",
    "_SCRIPTS_DIR": "_ctx",
    "_DEP_ID_RE": "depdag",
    "_RESERVED_DEP_PREFIXES": "depdag",
    "parse_dep_block": "depdag",
    "dep_ids": "depdag",
    "detect_dep_cycle": "depdag",
    "validate_dep_id_list": "depdag",
    "validate_queue_deps": "depdag",
    "sync_deps": "depdag",
    "dep_completion_status": "depdag",
    "format_unknown_dependency_blocker": "depdag",

    # Phase 2 WU-2: the document-model (parsing) seam.
    "_FENCE": "docmodel",
    "_FLAT_SCALAR_LINE_RE": "docmodel",
    "_yaml_load_tolerant": "docmodel",
    "_yaml_fallback_scalar": "docmodel",
    "parse_sentinel": "docmodel",
    "_PIPELINE_SKIPPED_BY": "docmodel",
    "_APP_SURFACE_MARKERS": "docmodel",
    "repo_has_no_app_surface": "docmodel",
    "repo_uses_cognito_planner": "docmodel",
    "phases_mcp_runtime_not_required": "docmodel",
    "phases_spike_required": "docmodel",          # harden Round 80 — spike header parse
    "_read_spike_decision": "docmodel",           # harden Round 80 — spike variant + goal
    "spike_verdict_is_pass": "docmodel",          # spike-pipeline-role Phase 2 WU-1 — verdict PASS reader
    "skip_waiver_refusal": "docmodel",
    "spec_status": "docmodel",
    "PROVISIONAL_SENTINEL": "docmodel",
    "_PROVISIONAL_ELIGIBLE_GRADES": "docmodel",
    "build_parked_entry": "docmodel",
    "_parse_plan_frontmatter": "docmodel",
    "_plan_status": "docmodel",
    "_VALID_PLAN_COMPLEXITIES": "docmodel",
    "_DEFAULT_PLAN_COMPLEXITY": "docmodel",
    "plan_complexity": "docmodel",
    "_plan_lowest_phase": "docmodel",
    "_PLAN_PART_RE": "docmodel",
    "_plan_series_index": "docmodel",
    "_plan_sort_key": "docmodel",
    "_plan_phase_set": "docmodel",
    "_unchecked_wus_in_plan_scope": "docmodel",
    "_all_wus_in_plan_scope": "docmodel",
    "find_implementation_plans": "docmodel",
    "_implementation_plans_exist": "docmodel",
    "_has_any_complete_plan": "docmodel",
    "find_retro_plans": "docmodel",
    "latest_retro_plan": "docmodel",
    "retro_plan_has_significant_divergences": "docmodel",
    "count_deliverables": "docmodel",
    "_VERIFICATION_ONLY_MARKER": "docmodel",
    "_VERIFICATION_SECTION_RE": "docmodel",
    "_DELIVERABLES_SECTION_RE": "docmodel",
    "_DESCOPE_STRIKETHROUGH_RE": "docmodel",
    "_DESCOPE_MARKER_RE": "docmodel",
    "_DESCOPED_MARKER": "docmodel",
    "_row_is_descoped_in_place": "docmodel",
    "_REQUIRES_HOST_ROW_RE": "docmodel",
    "_REQUIRES_HOST_CAP_ID_RE": "docmodel",
    "row_requires_host": "docmodel",
    "remaining_unchecked_are_verification_only": "docmodel",
    "classify_blocking_unchecked_rows": "docmodel",
    "enumerate_deferred_verification_rows": "docmodel",
    "_PHASE_HEADING_RE": "docmodel",
    "_BOLD_STATUS_RE": "docmodel",
    "_PHASE_KIND_RE": "docmodel",
    "_VALID_PHASE_KINDS": "docmodel",
    "_DEFAULT_PHASE_KIND": "docmodel",
    "parse_phases": "docmodel",
    "_IMPL_NOTES_HEADING_RE": "docmodel",
    "_SIBLING_IMPL_NOTES_HEADING_RE": "docmodel",
    "_sibling_impl_notes_present": "docmodel",
    "phases_show_implementation": "docmodel",
    "retro_staleness": "docmodel",
    "_TERMINAL_PHASE_STATUSES": "docmodel",
    "_phase_completion_plan": "docmodel",
    "_coerce_evidence_count": "docmodel",
    "_FAIL_CLOSED_EVIDENCE_SENTINELS": "docmodel",
    "_EVIDENCE_GATE_KILL_SWITCHES": "docmodel",
    "_FALSY_ENV_VALUES": "docmodel",
    "_evidence_gate_killed": "docmodel",

    # Phase 2 WU-3 (Batch 3): the host-capability declaration + probe seam.
    "_HOST_CAPABILITY_ID_RE": "hostcaps",
    "_HOST_CAPABILITY_REGISTRY": "hostcaps",
    "_coerce_capability_ids": "hostcaps",
    "_REQUIRES_HOST_RE": "hostcaps",
    "parse_requires_host": "hostcaps",
    "unknown_capability_ids": "hostcaps",
    "_HOST_PROBE_CACHE_FILENAME": "hostcaps",
    "_HOST_CAPABILITY_PROBE_CONFIG": "hostcaps",
    "_default_host_probes": "hostcaps",
    "host_present_capabilities": "hostcaps",
    "utc_now_iso": "hostcaps",
    "format_unknown_host_capability_blocker": "hostcaps",
    # Phase 2 WU-4 (Batch 4): the operator-halt notify plane (shim retired).
    "_NOTIFY_CONFIG_FILENAME": "notifyplane",
    "_NOTIFY_LEDGER_FILENAME": "notifyplane",
    "_NOTIFY_ERROR_FILENAME": "notifyplane",
    "_NOTIFY_SEND_TIMEOUT_SECONDS": "notifyplane",
    "_NOTIFY_LEDGER_MAX_AGE_SECONDS": "notifyplane",
    "_NOTIFY_ATTENTION_TERMINALS": "notifyplane",
    "_NOTIFY_CLEAN_STOP_TERMINALS": "notifyplane",
    "_NOTIFY_SENTINEL_CANDIDATES": "notifyplane",
    "_load_notify_config": "notifyplane",
    "_notify_sentinel_path": "notifyplane",
    "_notify_identity": "notifyplane",
    "_load_notify_ledger": "notifyplane",
    "_record_notify_send": "notifyplane",
    "_write_notify_error": "notifyplane",
    "_notify_decisions": "notifyplane",
    "_normalize_git_remote_url": "notifyplane",
    "_github_remote_url": "notifyplane",
    "_compose_notify_payload": "notifyplane",
    "_rfc2047_header": "notifyplane",
    "_ntfy_send": "notifyplane",
    "notify_halt": "notifyplane",
    "notify_event": "notifyplane",
    # Phase 2 WU-5 (Batch 5): the hook-touched state-dir surface (D4 cut).
    "_HOOK_EVENTS_FILENAME": "statedir",
    "_LEDGER_HEAD_CHARS": "statedir",
    "_LEGACY_STATE_FILENAMES": "statedir",
    "_MARKER_FILENAME": "statedir",
    "_REGISTRY_FILENAME": "statedir",
    "_load_registry": "statedir",
    "active_repo_root": "statedir",
    "append_hook_event": "statedir",
    "claude_state_dir": "statedir",
    "migrate_legacy_state_dir": "statedir",
    "repo_key": "statedir",
    "set_active_repo_root": "statedir",
    # Phase 4: the gates seam (completion-gate plane: evidence gate, autotick, structural backstop, verify-ledger).
    "_AUTOTICK_COMMENT_PREFIX": "gates",
    "_DETAIL_MAX_ITEMS": "gates",
    "_FOREIGN_HARDEN_SUBJECT_RE": "gates",
    "_PLAN_WU_CHECKBOX_RE": "gates",
    "_UNCHECKED_ROW_RE": "gates",
    "_commit_subject_is_foreign_harden": "gates",
    "_excerpt": "gates",
    "_files_from_commits": "gates",
    "_git_diff_name_only": "gates",
    "_is_noninvalidating_drift_path": "gates",
    "_item_commit_touched_files": "gates",
    "_load_control_surface_globs": "gates",
    "_load_harness_gate_module": "gates",
    "_load_validate_plan_module": "gates",
    "_manifest_glob_match": "gates",
    "_phases_text_scoped_to": "gates",
    "_phases_unchecked_row_detail": "gates",
    "_plan_unchecked_wus_are_verification_only": "gates",
    "_plan_wu_checkbox_counts": "gates",
    "_plan_wu_unchecked_row_detail": "gates",
    "autotick_verification_rows": "gates",
    "commit_drift_verdict": "gates",
    "evaluate_completion_evidence": "gates",
    "evaluate_deferred_runtime_exemption": "gates",
    "write_runtime_gates_ledger": "gates",
    "format_plan_structural_blocker": "gates",
    "gate_verdict_ok": "gates",
    "observation_gap_promotable": "gates",
    "plan_structural_backstop": "gates",
    "summarize_failing_detail": "gates",
    "verify_ledger": "gates",
    # Phase 4: the ledgers seam (ledger plane: deny/friction/telemetry ledgers, provenance, interventions, canary).
    "CANARY_WINDOW_DAYS_CEILING": "ledgers",
    "CANARY_WINDOW_RUNS_DEFAULT": "ledgers",
    "INTERVENTION_BAND_PCT": "ledgers",
    "INTERVENTION_BASELINE_RUNS": "ledgers",
    "INTERVENTION_MIN_SAMPLE": "ledgers",
    "INTERVENTION_REVIEW_AFTER_RUNS": "ledgers",
    "TELEMETRY_HALT_TERMINAL_REASONS": "ledgers",
    "_CANARY_CLAUDE_MD_PAIRS": "ledgers",
    "_CANARY_CONTROL_SURFACES_FALLBACK": "ledgers",
    "_CANARY_CONTROL_SURFACES_FILE": "ledgers",
    "_CANARY_DEFAULT_REVERT_UNSAFE_NOTE": "ledgers",
    "_COMMIT_BRACKETS_FILENAME": "ledgers",
    "_DENY_LEDGER_FILENAME": "ledgers",
    "_EFFICACY_BREADCRUMB_FILENAME": "ledgers",
    "_GATE_REFUSAL_SIGNATURES": "ledgers",
    "_GUARD_PLANE_HEARTBEAT_MIN_CYCLES": "ledgers",
    "_INTERVENTIONS_DIRNAME": "ledgers",
    "_INTERVENTION_EVENT_VOCABULARY": "ledgers",
    "_INTERVENTION_FIELD_ORDER": "ledgers",
    "_INTERVENTION_FIELD_RE": "ledgers",
    "_INTERVENTION_HYPOTHESIS_HEADING_RE": "ledgers",
    "_INTERVENTION_INDEPENDENCE_ENUM": "ledgers",
    "_INTERVENTION_INT_FIELDS": "ledgers",
    "_INTERVENTION_SUB_SIGNAL_VOCABULARY": "ledgers",
    "_OBSERVED_FRICTION_PROBE_PLACEHOLDER": "ledgers",
    "_OBSERVED_FRICTION_REGISTRY_PLACEHOLDER": "ledgers",
    "_PROVENANCE_CHURN_DAYS": "ledgers",
    "_PROVENANCE_CHURN_THRESHOLD": "ledgers",
    "_PROVENANCE_KINDS": "ledgers",
    "_PROVENANCE_VALUES": "ledgers",
    "_TELEMETRY_LEDGER_FILENAME": "ledgers",
    "_TELEMETRY_ROTATED_SEGMENTS": "ledgers",
    "_TELEMETRY_ROTATE_BYTES": "ledgers",
    "_TELEMETRY_SCHEMA_VERSION": "ledgers",
    "_canary_control_surfaces": "ledgers",
    "_canary_glob_to_re": "ledgers",
    "_canary_intersects": "ledgers",
    "_canary_load_parity_pairs": "ledgers",
    "_canary_touched_files": "ledgers",
    "_compute_pair_scope": "ledgers",
    "_deny_entry_same_cause_key": "ledgers",
    "_git_capture_lines": "ledgers",
    "_intervention_signal_event": "ledgers",
    "_intervention_signal_signature": "ledgers",
    "_interventions_queue_flag": "ledgers",
    "_iter_receipted_item_dirs": "ledgers",
    "_maybe_arm_canary": "ledgers",
    "_normalize_index_key": "ledgers",
    "_originating_telemetry_paths": "ledgers",
    "_provenance_doc_path": "ledgers",
    "_provenance_index_path": "ledgers",
    "_raw_marker_started_at": "ledgers",
    "_render_intervention_record": "ledgers",
    "_repo_is_interventions_bearing": "ledgers",
    "_resolve_pr_range": "ledgers",
    "_resolve_provenance_item_dir": "ledgers",
    "_rotate_telemetry_segments": "ledgers",
    "_run_marker_state_dir": "ledgers",
    "_spec_summary_paragraph": "ledgers",
    "_telemetry_run_marker": "ledgers",
    "ack_all_unacked_denies": "ledgers",
    "ack_deny_by_selector": "ledgers",
    "ack_oldest_deny": "ledgers",
    "append_auto_readmit_event": "ledgers",
    "append_commit_bracket": "ledgers",
    "append_concurrent_commit_sha": "ledgers",
    "append_deny_ledger_entry": "ledgers",
    "append_friction_ledger_entry": "ledgers",
    "append_telemetry_event": "ledgers",
    "backfill_provenance": "ledgers",
    "build_hardening_emit_command": "ledgers",
    "flush_commit_artifacts": "ledgers",
    "clear_efficacy_breadcrumb": "ledgers",
    "derive_touched_from_brackets": "ledgers",
    "derive_touched_from_grep": "ledgers",
    "derive_touched_from_range": "ledgers",
    "drop_efficacy_breadcrumb": "ledgers",
    "efficacy_breadcrumb_present": "ledgers",
    "find_auto_readmit_entry": "ledgers",
    "find_transcription_slip_entry": "ledgers",
    "flush_cloud_telemetry_segment": "ledgers",
    "guard_plane_heartbeat": "ledgers",
    "link_provenance": "ledgers",
    "lint_provenance": "ledgers",
    "normalize_hardening_dispatch_context": "ledgers",
    "oldest_unacked_deny": "ledgers",
    "parse_intervention_hypothesis": "ledgers",
    "pending_denial_reasons": "ledgers",
    "pending_hardening": "ledgers",
    "prior_run_pending_hardening": "ledgers",
    "provenance_lookup": "ledgers",
    "read_commit_brackets": "ledgers",
    "read_concurrent_commit_entries": "ledgers",
    "read_deny_ledger": "ledgers",
    "read_hook_events": "ledgers",
    "read_intervention_telemetry": "ledgers",
    "read_telemetry_events": "ledgers",
    "record_cycle_commit_bracket": "ledgers",
    "record_intervention": "ledgers",
    "validate_intervention_target_signal": "ledgers",
    "write_provenance": "ledgers",
    # Phase 4: the dispatch seam (dispatch plane: cycle/dispatch prompt emission, skill-frontmatter readers, prompt registry).
    "DISPATCH_CLASSES": "dispatch",
    "DISPATCH_MODELS": "dispatch",
    "DISPATCH_STEP_NAMES": "dispatch",
    "_COMMIT_CADENCE_MULTI_FLAG_RE": "dispatch",
    "_CYCLE_COMMIT_BUDGET_DEFAULT": "dispatch",
    "_CYCLE_COMMIT_MULTI": "dispatch",
    "_CYCLE_COMMIT_NOISE_ALLOWANCE": "dispatch",
    "_CYCLE_TEMPLATE_DIRNAME": "dispatch",
    "_DISPATCH_REQUIRES_RE": "dispatch",
    "_MULTI_COMMIT_CEILING_OVERRIDE": "dispatch",
    "_MULTI_COMMIT_PSEUDO_SKILLS": "dispatch",
    "_NORM_FOLD_TABLE": "dispatch",
    "_PROMPT_RESIDUE_RE": "dispatch",
    "_SECTION_MARKER_RE": "dispatch",
    "_SUBAGENT_MODEL_FLAG_RE": "dispatch",
    "_csv_set": "dispatch",
    "_dedup_residue": "dispatch",
    "_default_cycle_template_dir": "dispatch",
    "_emit_work_branch": "dispatch",
    "_mcp_test_cycle_model": "dispatch",
    "_parse_cycle_template": "dispatch",
    "_parse_section_attrs": "dispatch",
    "_read_mcp_runtime_decision": "dispatch",
    "_save_registry": "dispatch",
    "_standard_dispatch_bindings": "dispatch",
    "_strip_loop_fence": "dispatch",
    "append_dispatch_by_reference_event": "dispatch",
    "append_worker_subdispatch_event": "dispatch",
    "append_claude_code_guide_consult_event": "dispatch",
    "consume_nonce": "dispatch",
    "consumed_emission_count": "dispatch",
    "emission_consumed_by_nonce": "dispatch",
    "emit_cycle_prompt": "dispatch",
    "emit_dispatch_prompt": "dispatch",
    "load_context_json": "dispatch",
    "lookup_emission": "dispatch",
    "normalize_prompt_for_hash": "dispatch",
    "prompt_sha256": "dispatch",
    "register_emission": "dispatch",
    "register_emission_if_marked": "dispatch",
    "registry_summary": "dispatch",
    "resolve_consumed_emission_by_nonce": "dispatch",
    "resolve_emission_by_nonce": "dispatch",
    "skill_declares_multi_commit": "dispatch",
    "skill_declares_subagent_model": "dispatch",
    # Phase 4: the runtimeplane seam (runtime plane: ensure_runtime/M4, spawn, transient build, runtime lock, capability probes).
    "_BINARY_PROBE_TIMEOUT_SECONDS": "runtimeplane",
    "_BOOT_SPAWN_GRACE_SECONDS": "runtimeplane",
    "_BOOT_STAMP_FILENAME": "runtimeplane",
    "_COLD_COMPILE_WAIT_INTERVAL": "runtimeplane",
    "_COLD_COMPILE_WAIT_MAX_POLLS": "runtimeplane",
    "_COMPILE_WENT_DEAD": "runtimeplane",
    "_CREATE_BREAKAWAY_FROM_JOB": "runtimeplane",
    "_CREATE_NEW_PROCESS_GROUP": "runtimeplane",
    "_DETACHED_PROCESS": "runtimeplane",
    "_ENSURE_RUNTIME_DEFAULT_CONFIG": "runtimeplane",
    "_FILETIME_EPOCH_OFFSET": "runtimeplane",
    "_FILETIME_TICKS_PER_SEC": "runtimeplane",
    "_LEGACY_STATUS_TO_STATE": "runtimeplane",
    "_PLATFORM_PREDICATES": "runtimeplane",
    "_RUNTIME_RECOVERY_BACKOFF_BASE": "runtimeplane",
    "_RUNTIME_RECOVERY_MAX_ATTEMPTS": "runtimeplane",
    "_RUNTIME_STATES": "runtimeplane",
    "_await_compile_serving": "runtimeplane",
    "_blocked_blocker": "runtimeplane",
    "_boot_stamp_path": "runtimeplane",
    "_classify_compile_state": "runtimeplane",
    "_cold_compile_timeout_blocker": "runtimeplane",
    "_default_build_wait": "runtimeplane",
    "_default_frontend_probe": "runtimeplane",
    "_default_git_clean_staging": "runtimeplane",
    "_default_runtime_probe": "runtimeplane",
    "_default_sidecar_probe": "runtimeplane",
    "_default_stale_check": "runtimeplane",
    "_ensure_runtime_m4": "runtimeplane",
    "_hijacked_blocker": "runtimeplane",
    "_mcp_tool_in_payload": "runtimeplane",
    "_mcp_tools_present_honest": "runtimeplane",
    "_posix_boot_time": "runtimeplane",
    "_recover_runtime": "runtimeplane",
    "_route_legacy_non_serving": "runtimeplane",
    "_runtime_lock_path": "runtimeplane",
    "_runtime_verdict": "runtimeplane",
    "_sidecar_is_connected": "runtimeplane",
    "_win_process_creation_filetime": "runtimeplane",
    "boot_recently_spawned": "runtimeplane",
    "ensure_runtime": "runtimeplane",
    "kernel_start_time": "runtimeplane",
    "probe_binary_capability": "runtimeplane",
    "probe_env_capability": "runtimeplane",
    "probe_platform_capability": "runtimeplane",
    "promote_artifact_atomically": "runtimeplane",
    "read_boot_stamp": "runtimeplane",
    "read_runtime_lock": "runtimeplane",
    "reconcile_cycle_begin_git_consistency": "runtimeplane",
    "run_transient_build": "runtimeplane",
    "spawn_detached": "runtimeplane",
    "verify_runtime_ownership": "runtimeplane",
    "write_boot_stamp": "runtimeplane",
    "write_runtime_lock": "runtimeplane",
    # Phase 4: the markers seam (marker plane: run/cycle markers, ownership, refusals, checkpoints, budget counters, friction detector).
    "AUDITED_CYCLE_KINDS": "markers",
    "CYCLE_REFUSED_OPS": "markers",
    "RUN_CONTINUITY_FIELDS": "markers",
    "RUN_FRESH_FIELDS": "markers",
    "SANCTIONED_STOP_TERMINAL": "markers",
    "SANCTIONED_LANE_PARK_TERMINAL": "markers",
    "_CHECKPOINT_FILENAME": "markers",
    "_CYCLE_MARKER_FILENAME": "markers",
    "_EXECUTE_PLAN_BOOKEND_COMMITS": "markers",
    "_EXECUTE_PLAN_PHASE_BUDGET_SLACK": "markers",
    "_FORWARD_ADVANCING_PSEUDO_SKILLS": "markers",
    "_MARKER_STALE_SECONDS": "markers",
    "_bump_per_feature_forward": "markers",
    "_consume_resolution_signal": "markers",
    "_count_authored_commits_since": "markers",
    "_count_concurrent_writer_commits": "markers",
    "_env_truthy": "markers",
    "_execute_plan_commit_budget": "markers",
    "_execute_plan_marker_path": "markers",
    "execute_plan_liveness": "markers",
    "_run_marker_scoped_keys": "markers",
    "advance_cycle_bracket_counter": "markers",
    "advance_forward_cycle": "markers",
    "advance_meta_cycle": "markers",
    "advance_run_counters": "markers",
    "bind_marker_session": "markers",
    "budget_trip_signals": "markers",
    "clear_cycle_marker": "markers",
    "compute_per_feature_ceiling": "markers",
    "consume_run_checkpoint": "markers",
    "count_validation_corrective_cycles": "markers",
    "current_branch_snapshot": "markers",
    "cycle_end_friction_check": "markers",
    "delete_run_marker": "markers",
    "detect_cycle_bracket_friction": "markers",
    "discharge_audit_obligation": "markers",
    "feature_is_near_complete": "markers",
    "fold_max_cycles": "markers",
    "fold_park_flags": "markers",
    "fold_run_counters": "markers",
    "head_sha_snapshot": "markers",
    "head_commit_subject": "markers",
    "marker_owner_status": "markers",
    "marker_work_branch": "markers",
    "parse_parent_run_arg": "markers",
    "pending_audit_obligation": "markers",
    "read_cycle_marker": "markers",
    "read_per_feature_forward_cycles": "markers",
    "read_run_marker": "markers",
    "reassert_marker_owner": "markers",
    "rebaseline_loop_signature_after_registry_reset": "markers",
    "record_audit_obligation": "markers",
    "record_corrective_cycle": "markers",
    "record_resolution_signal": "markers",
    "refuse_cycle_marker_mutation_if_subagent": "markers",
    "refuse_if_cycle_active": "markers",
    "refuse_run_start_clobber": "markers",
    "resolve_cycle_worker_nonce": "markers",
    "restore_checkpoint_counters": "markers",
    "set_marker_max_cycles": "markers",
    "set_marker_park": "markers",
    "update_repeat_count": "markers",
    "update_repeat_counts": "markers",
    "write_cycle_marker": "markers",
    "write_run_checkpoint": "markers",
    "write_run_marker": "markers",
    # Phase 4: the pseudo seam (pseudo-skill apply plane: apply_pseudo (moved INTACT) + completion post-condition audit + ROADMAP strike helpers).
    "_ROADMAP_COMPLETE_TOKEN": "pseudo",
    "_completion_postconditions_missing": "pseudo",
    "_resolve_under_repo": "pseudo",
    "_roadmap_has_unstruck_row": "pseudo",
    "_strike_roadmap_row": "pseudo",
    "_top_status_is": "pseudo",
    "apply_pseudo": "pseudo",
    # Phase 5 WU-3: the kernel error-exit helper.
    "_die": "_ctx",
    # Phase 5 WU-3: queue mutation ops + merged ordering plane + skip-ahead.
    "MERGED_PRIORITY_DEFAULT": "depdag",
    "_AGE_ESCALATION_FLOOR_RANK": "depdag",
    "_AGE_ESCALATION_QUANTUM_DAYS": "depdag",
    "_MERGED_SEVERITY_RANK": "depdag",
    "_FEATURE_TIER_ENUM": "depdag",
    "_resolve_feature_tier_element": "depdag",
    "_MERGED_TYPE_ORDER": "depdag",
    "_PIN_DEFAULT_MAX_AGE_DAYS": "depdag",
    "age_escalated_rank": "depdag",
    "bug_priority_marker": "depdag",
    "clear_queue_stub": "depdag",
    "merged_priority": "depdag",
    "merged_worklist": "depdag",
    "next_merged": "depdag",
    "pin_is_active": "depdag",
    "reorder_queue": "depdag",
    # no-sanctioned-cli-for-queue-state-mutations: operator-directed in-place
    # priority/dependency mutators (--set-severity/--set-tier/--add-deps/
    # --remove-deps engines) + the atomic listed-order reposition.
    "reposition_by_priority": "depdag",
    "set_queue_priority": "depdag",
    "mutate_queue_deps": "depdag",
    "set_independent_marker": "depdag",
    "skip_ahead_ready": "depdag",
    # Phase 5 WU-3: receipt writers, validation escalation, archive-on-fix, gate-coverage plane.
    "VALIDATION_ESCALATION_SUFFIX": "gates",
    "_GATE_COVERAGE_STOPWORDS": "gates",
    "_gate_coverage_keywords": "gates",
    "_parse_locked_decisions": "gates",
    "_parse_mcp_coverage_exemptions": "gates",
    "_resolve_scenario_text": "gates",
    "archive_fixed": "gates",
    "gate_coverage": "gates",
    "has_completion_receipt": "gates",
    "spike_escalation": "gates",
    "spike_tooling_cap_exceeded": "gates",
    "validation_escalation": "gates",
    "write_completed_receipt": "gates",
    # Phase 5 WU-3: feature-dir state ledgers (stale-upstream, materialized, WIP/stage, decisions) + input-audit emit command.
    "_DECISIONS_FILENAME": "ledgers",
    "_MATERIALIZED_FILENAME": "ledgers",
    "_REVIEWED_FILENAME": "ledgers",
    "_STALE_UPSTREAM_FILENAME": "ledgers",
    "_WIP_FILENAME": "ledgers",
    "_load_decisions": "ledgers",
    "_normalize_sentinel_key": "ledgers",
    "_write_wip": "ledgers",
    "append_materialized": "ledgers",
    "bind_decision_record_context": "ledgers",
    "build_input_audit_emit_command": "ledgers",
    "clear_stale_upstream": "ledgers",
    "derive_stage": "ledgers",
    "read_decision_record": "ledgers",
    "read_materialized": "ledgers",
    "read_stale_upstream": "ledgers",
    "record_decision": "ledgers",
    "track_close": "ledgers",
    "track_open": "ledgers",
    "track_touch": "ledgers",
    "update_materialized_changeddate": "ledgers",
    "write_stale_upstream": "ledgers",
    # Phase 5 WU-3: sentinel lifecycle (noncanonical/neutralize/provisional) + independent-marker parse.
    "_INDEPENDENT_MARKER_KEYS": "docmodel",
    "_INDEPENDENT_MARKER_RE": "docmodel",
    "_coerce_marker_truthy": "docmodel",
    "_extract_recommended_label": "docmodel",
    "_split_decision_context_h3s": "docmodel",
    "classify_conflict": "docmodel",
    "detect_noncanonical_blocker": "docmodel",
    "neutralize_sentinel": "docmodel",
    "parse_independent_marker": "docmodel",
    "provisional_eligibility": "docmodel",
    "provisionalize_sentinel": "docmodel",
    "spec_dir_operator_deferred": "docmodel",
    "spec_dir_research_pending": "docmodel",
    "spec_dir_would_park": "docmodel",
    "write_spike_tooling_cap_needs_input": "docmodel",
    # Phase 5 WU-3: git helpers + self-edit detection.
    "GOVERNING_FILE_SET": "runtimeplane",
    "_current_head": "runtimeplane",
    "_git": "runtimeplane",
    "compose_concurrent_merge_back_trailer": "runtimeplane",
    "parse_concurrent_merge_back_trailer": "runtimeplane",
    "read_concurrent_merge_back_trailers": "runtimeplane",
    "git_guard_status": "runtimeplane",
    "git_head_short_sha": "runtimeplane",
    "git_safe_push": "runtimeplane",
    "governing_files_touched": "runtimeplane",
    "self_edit_mode": "runtimeplane",
    # Phase 5 WU-3: cycle-header formatter + prompt-registry constants.
    "REGISTRY_ENTRY_TTL_SECONDS": "dispatch",
    "SUB_SKILL_STEP_NAMES": "dispatch",
    "_REGISTRY_RING_CAP": "dispatch",
    "format_cycle_header": "dispatch",
    # Phase 5 WU-3: the host-plane sentinel writer.
    "write_deferred_requires_host": "hostcaps",
    # Phase 5 WU-4: explicit-total sweep — the _ctx accessor plane (previously
    # fallback-shadowed; never monolith-resident).
    "_active_repo_root": "_ctx",
    "_legacy_state_migrated": "_ctx",
    "get_active_repo_root": "_ctx",
    "legacy_state_migrated": "_ctx",
    "set_active_repo_root_value": "_ctx",
    "set_legacy_state_migrated": "_ctx",
}

# All submodules that make up this package, in no particular order.
_ALL_SUBMODULES = ("_ctx", "depdag", "dispatch", "docmodel", "gates", "hostcaps", "ledgers", "markers", "notifyplane", "pseudo", "runtimeplane", "statedir")


def __getattr__(name):
    # Attribute access to a submodule name itself (e.g. `lazy_core.markers`)
    # must return the submodule object — a submodule doesn't have itself as
    # an attribute.
    if name in _ALL_SUBMODULES:
        return importlib.import_module(f".{name}", __name__)

    modname = _SUBMODULE_BY_NAME.get(name)
    if modname is None:
        raise AttributeError(f"module 'lazy_core' has no attribute {name!r}")
    mod = importlib.import_module(f".{modname}", __name__)
    try:
        return getattr(mod, name)
    except AttributeError:
        raise AttributeError(f"module 'lazy_core' has no attribute {name!r}") from None


def __dir__():
    names = set(globals().keys()) | set(_SUBMODULE_BY_NAME.keys()) | set(_ALL_SUBMODULES)
    return sorted(names)


def load_all():
    """Eagerly import every submodule in this package.

    For consumers that want ImportError timing pinned to process start
    rather than first attribute access. Not wired into any state script in
    this WU — a later WU wires this into lazy-state.py / bug-state.py.
    """
    for submodule in _ALL_SUBMODULES:
        importlib.import_module(f".{submodule}", __name__)
